/**
 * Shared demo training accounts + sample progress for seed + memory store.
 * DEMO passwords only — never real credentials.
 */

export const CORE_ACCOUNTS = [
  {
    username: "trainee001",
    password: "Train@Demo1",
    displayName: "Corporal Rahman",
    rank: "Cpl",
    unit: "Signals Battalion",
    department: "Signals",
    role: "trainee",
  },
  {
    username: "trainee002",
    password: "Train@Demo2",
    displayName: "Lance Naik Karim",
    rank: "L/Nk",
    unit: "Infantry Regiment",
    department: "Infantry",
    role: "trainee",
  },
  {
    username: "instructor001",
    password: "Instruct@Demo1",
    displayName: "Major Hasan",
    rank: "Maj",
    unit: "Cyber Defence Wing",
    department: "Cyber",
    role: "instructor",
  },
  {
    username: "admin001",
    password: "Admin@Demo1",
    displayName: "Colonel Rahman",
    rank: "Col",
    unit: "Cyber Defence Wing",
    department: "Cyber",
    role: "admin",
  },
];

/** Additional trainees for live instructor analytics across departments */
export const EXTRA_TRAINEES = [
  {
    username: "trainee003",
    password: "Train@Demo3",
    displayName: "Sergeant Akter",
    rank: "Sgt",
    unit: "Artillery Brigade",
    department: "Artillery",
    role: "trainee",
  },
  {
    username: "trainee004",
    password: "Train@Demo4",
    displayName: "Havildar Islam",
    rank: "Hav",
    unit: "Engineer Corps",
    department: "Engineers",
    role: "trainee",
  },
  {
    username: "trainee005",
    password: "Train@Demo5",
    displayName: "Captain Noor",
    rank: "Capt",
    unit: "Cyber Defence Wing",
    department: "Cyber",
    role: "trainee",
  },
  {
    username: "trainee006",
    password: "Train@Demo6",
    displayName: "Naik Hassan",
    rank: "Nk",
    unit: "Logistics Command",
    department: "Logistics",
    role: "trainee",
  },
  {
    username: "trainee007",
    password: "Train@Demo7",
    displayName: "Warrant Officer Reza",
    rank: "WO",
    unit: "Signals Battalion",
    department: "Signals",
    role: "trainee",
  },
  {
    username: "trainee008",
    password: "Train@Demo8",
    displayName: "Private Chowdhury",
    rank: "Pte",
    unit: "Infantry Regiment",
    department: "Infantry",
    role: "trainee",
  },
  {
    username: "trainee009",
    password: "Train@Demo9",
    displayName: "Corporal Fatema",
    rank: "Cpl",
    unit: "Signals Battalion",
    department: "Signals",
    role: "trainee",
  },
  {
    username: "trainee010",
    password: "Train@Demo10",
    displayName: "Lance Naik Kabir",
    rank: "L/Nk",
    unit: "Artillery Brigade",
    department: "Artillery",
    role: "trainee",
  },
  {
    username: "trainee011",
    password: "Train@Demo11",
    displayName: "Sergeant Parveen",
    rank: "Sgt",
    unit: "Engineer Corps",
    department: "Engineers",
    role: "trainee",
  },
  {
    username: "trainee012",
    password: "Train@Demo12",
    displayName: "Naik Yusuf",
    rank: "Nk",
    unit: "Logistics Command",
    department: "Logistics",
    role: "trainee",
  },
  {
    username: "trainee013",
    password: "Train@Demo13",
    displayName: "Private Anika",
    rank: "Pte",
    unit: "Infantry Regiment",
    department: "Infantry",
    role: "trainee",
  },
  {
    username: "trainee014",
    password: "Train@Demo14",
    displayName: "Havildar Saleh",
    rank: "Hav",
    unit: "Cyber Defence Wing",
    department: "Cyber",
    role: "trainee",
  },
  {
    username: "trainee015",
    password: "Train@Demo15",
    displayName: "Corporal Mehedi",
    rank: "Cpl",
    unit: "Signals Battalion",
    department: "Signals",
    role: "trainee",
  },
  {
    username: "trainee016",
    password: "Train@Demo16",
    displayName: "Lance Corporal Rafi",
    rank: "L/Cpl",
    unit: "Artillery Brigade",
    department: "Artillery",
    role: "trainee",
  },
  {
    username: "instructor002",
    password: "Instruct@Demo2",
    displayName: "Captain Jahan",
    rank: "Capt",
    unit: "Cyber Defence Wing",
    department: "Cyber",
    role: "instructor",
  },
];

export const ALL_SEED_ACCOUNTS = [...CORE_ACCOUNTS, ...EXTRA_TRAINEES];

export const MODULE_IDS = [
  "email-phishing",
  "fake-login",
  "qr-phishing",
  "sms-phishing",
  "voice-phishing",
  "usb-security",
  "password-security",
  "social-engineering",
];

/**
 * Sample progress rows: username, moduleId, score, completed, monthsAgo (for trend)
 */
export const SAMPLE_PROGRESS = [
  { username: "trainee001", moduleId: "email-phishing", score: 90, completed: true, monthsAgo: 2 },
  { username: "trainee001", moduleId: "fake-login", score: 85, completed: true, monthsAgo: 2 },
  { username: "trainee001", moduleId: "qr-phishing", score: 88, completed: true, monthsAgo: 1 },
  { username: "trainee001", moduleId: "sms-phishing", score: 82, completed: true, monthsAgo: 1 },
  { username: "trainee001", moduleId: "voice-phishing", score: 80, completed: true, monthsAgo: 0 },
  { username: "trainee002", moduleId: "email-phishing", score: 78, completed: true, monthsAgo: 3 },
  { username: "trainee002", moduleId: "fake-login", score: 70, completed: true, monthsAgo: 2 },
  { username: "trainee002", moduleId: "sms-phishing", score: 74, completed: true, monthsAgo: 1 },
  { username: "trainee003", moduleId: "email-phishing", score: 95, completed: true, monthsAgo: 4 },
  { username: "trainee003", moduleId: "fake-login", score: 92, completed: true, monthsAgo: 4 },
  { username: "trainee003", moduleId: "qr-phishing", score: 94, completed: true, monthsAgo: 3 },
  { username: "trainee003", moduleId: "sms-phishing", score: 96, completed: true, monthsAgo: 3 },
  { username: "trainee003", moduleId: "voice-phishing", score: 93, completed: true, monthsAgo: 2 },
  { username: "trainee003", moduleId: "usb-security", score: 91, completed: true, monthsAgo: 1 },
  { username: "trainee003", moduleId: "password-security", score: 97, completed: true, monthsAgo: 1 },
  { username: "trainee003", moduleId: "social-engineering", score: 94, completed: true, monthsAgo: 0 },
  { username: "trainee004", moduleId: "email-phishing", score: 84, completed: true, monthsAgo: 2 },
  { username: "trainee004", moduleId: "fake-login", score: 80, completed: true, monthsAgo: 2 },
  { username: "trainee004", moduleId: "qr-phishing", score: 78, completed: true, monthsAgo: 1 },
  { username: "trainee004", moduleId: "sms-phishing", score: 81, completed: true, monthsAgo: 1 },
  { username: "trainee004", moduleId: "usb-security", score: 85, completed: true, monthsAgo: 0 },
  { username: "trainee004", moduleId: "password-security", score: 79, completed: true, monthsAgo: 0 },
  { username: "trainee005", moduleId: "email-phishing", score: 98, completed: true, monthsAgo: 5 },
  { username: "trainee005", moduleId: "fake-login", score: 97, completed: true, monthsAgo: 4 },
  { username: "trainee005", moduleId: "qr-phishing", score: 96, completed: true, monthsAgo: 4 },
  { username: "trainee005", moduleId: "sms-phishing", score: 99, completed: true, monthsAgo: 3 },
  { username: "trainee005", moduleId: "voice-phishing", score: 95, completed: true, monthsAgo: 3 },
  { username: "trainee005", moduleId: "usb-security", score: 94, completed: true, monthsAgo: 2 },
  { username: "trainee005", moduleId: "password-security", score: 100, completed: true, monthsAgo: 1 },
  { username: "trainee005", moduleId: "social-engineering", score: 97, completed: true, monthsAgo: 0 },
  { username: "trainee006", moduleId: "email-phishing", score: 60, completed: true, monthsAgo: 1 },
  { username: "trainee006", moduleId: "fake-login", score: 55, completed: true, monthsAgo: 0 },
  { username: "trainee007", moduleId: "email-phishing", score: 92, completed: true, monthsAgo: 3 },
  { username: "trainee007", moduleId: "fake-login", score: 90, completed: true, monthsAgo: 3 },
  { username: "trainee007", moduleId: "qr-phishing", score: 88, completed: true, monthsAgo: 2 },
  { username: "trainee007", moduleId: "sms-phishing", score: 91, completed: true, monthsAgo: 2 },
  { username: "trainee007", moduleId: "voice-phishing", score: 89, completed: true, monthsAgo: 1 },
  { username: "trainee007", moduleId: "usb-security", score: 87, completed: true, monthsAgo: 1 },
  { username: "trainee007", moduleId: "password-security", score: 93, completed: true, monthsAgo: 0 },
  { username: "trainee008", moduleId: "email-phishing", score: 70, completed: true, monthsAgo: 0 },
  { username: "trainee009", moduleId: "email-phishing", score: 86, completed: true, monthsAgo: 2 },
  { username: "trainee009", moduleId: "fake-login", score: 84, completed: true, monthsAgo: 1 },
  { username: "trainee009", moduleId: "qr-phishing", score: 80, completed: true, monthsAgo: 0 },
  { username: "trainee010", moduleId: "email-phishing", score: 88, completed: true, monthsAgo: 1 },
  { username: "trainee010", moduleId: "fake-login", score: 82, completed: true, monthsAgo: 1 },
  { username: "trainee010", moduleId: "sms-phishing", score: 85, completed: true, monthsAgo: 0 },
  { username: "trainee011", moduleId: "email-phishing", score: 75, completed: true, monthsAgo: 2 },
  { username: "trainee011", moduleId: "usb-security", score: 77, completed: true, monthsAgo: 1 },
  { username: "trainee011", moduleId: "password-security", score: 80, completed: true, monthsAgo: 0 },
  { username: "trainee012", moduleId: "email-phishing", score: 58, completed: true, monthsAgo: 0 },
  { username: "trainee014", moduleId: "email-phishing", score: 91, completed: true, monthsAgo: 2 },
  { username: "trainee014", moduleId: "fake-login", score: 89, completed: true, monthsAgo: 2 },
  { username: "trainee014", moduleId: "qr-phishing", score: 90, completed: true, monthsAgo: 1 },
  { username: "trainee014", moduleId: "social-engineering", score: 92, completed: true, monthsAgo: 0 },
  { username: "trainee015", moduleId: "email-phishing", score: 83, completed: true, monthsAgo: 1 },
  { username: "trainee015", moduleId: "fake-login", score: 81, completed: true, monthsAgo: 0 },
  { username: "trainee016", moduleId: "email-phishing", score: 72, completed: true, monthsAgo: 0 },
];

/** Count-only sim events for instructor click/form metrics */
export const SAMPLE_SIM_EVENTS = [
  { username: "trainee001", moduleId: "email-phishing", kind: "click", count: 4 },
  { username: "trainee001", moduleId: "fake-login", kind: "form_attempt", count: 2 },
  { username: "trainee001", moduleId: "fake-login", kind: "click", count: 3 },
  { username: "trainee002", moduleId: "email-phishing", kind: "click", count: 8 },
  { username: "trainee002", moduleId: "fake-login", kind: "form_attempt", count: 4 },
  { username: "trainee002", moduleId: "sms-phishing", kind: "click", count: 5 },
  { username: "trainee006", moduleId: "email-phishing", kind: "click", count: 12 },
  { username: "trainee006", moduleId: "fake-login", kind: "form_attempt", count: 6 },
  { username: "trainee006", moduleId: "sms-phishing", kind: "click", count: 7 },
  { username: "trainee008", moduleId: "email-phishing", kind: "click", count: 9 },
  { username: "trainee008", moduleId: "fake-login", kind: "form_attempt", count: 3 },
  { username: "trainee012", moduleId: "email-phishing", kind: "click", count: 10 },
  { username: "trainee012", moduleId: "qr-phishing", kind: "click", count: 6 },
  { username: "trainee013", moduleId: "sms-phishing", kind: "click", count: 8 },
  { username: "trainee003", moduleId: "email-phishing", kind: "click", count: 2 },
  { username: "trainee005", moduleId: "fake-login", kind: "form_attempt", count: 1 },
  { username: "trainee007", moduleId: "social-engineering", kind: "click", count: 3 },
];

export const DEPARTMENTS = [
  "Signals",
  "Infantry",
  "Artillery",
  "Engineers",
  "Cyber",
  "Logistics",
  "Aviation",
  "Medical",
];

export function completedAtFromMonthsAgo(monthsAgo) {
  const d = new Date();
  d.setMonth(d.getMonth() - (monthsAgo || 0));
  d.setDate(Math.max(1, d.getDate() - (monthsAgo || 0) * 2));
  return d.toISOString();
}
